### ISSUE TITLE
Maven build fails

### ISSUE THREAD

**Issue by vkroz** [before/uadetector#138]
on commit e0520105733ba61256064c9d85822b804ae9fc81
Date:   Sat Jul 25 19:11:44 2015 +0200

maven build fails
```
$ mvn package
	Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.RuntimeException: Class java/util/UUID could not be instrumented.
	at org.jacoco.agent.rt.internal_5d10cad.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:138)
	at org.jacoco.agent.rt.internal_5d10cad.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:99)
	at org.jacoco.agent.rt.internal_5d10cad.PreMain.createRuntime(PreMain.java:51)
	at org.jacoco.agent.rt.internal_5d10cad.PreMain.premain(PreMain.java:43)
	... 6 more
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
	at java.lang.Class.getField(Class.java:1703)
	at org.jacoco.agent.rt.internal_5d10cad.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:136)
	... 9 more
FATAL ERROR in native method: processing of -javaagent failed

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] UADetector ......................................... SUCCESS [  0.109 s]
[INFO] UADetector :: Core ................................. FAILURE [  1.102 s]
[INFO] UADetector :: Resources ............................ SKIPPED
[INFO] UADetector :: Distribution ......................... SKIPPED
```

**Comment by HaraldWalker** [comment]
Updating the jacoco version seems to fix that.
`<jacoco.version>0.8.2</jacoco.version>`
and I've also changed
`<java.version>1.8</java.version>`
Now trying to solve a failing unit test in CachingXmlDataStoreTest.

**Comment by godenji** [comment]
> Now trying to solve a failing unit test in CachingXmlDataStoreTest_deleteCacheFile

I hit the same a couple of months ago after attempting to migrate to Java 8.

**Comment by HaraldWalker** [comment]
@godenji I just updated that test and it now passes on Java 8. Complete build with tests etc. is now working again.

**Comment by godenji** [comment]
Great, go ahead and issue a PR when you get the chance.

**Comment by HaraldWalker** [comment]
@godenji I just did. Sorry, it includes some additional changes that I had already made. But I think those are all fine.
Going to test now with current version of the UAS database to see if anything needs to be updated.

**Comment by godenji** [comment]
Nice, just pulled your PR locally; all tests pass on Java 8 -- merged, closing this issue.
